# @package trainer
_target_: lightning.pytorch.Trainer
accelerator: mps
devices: 1
max_epochs: 1
log_every_n_steps: 10
enable_checkpointing: true
enable_progress_bar: true
deterministic: false
gradient_clip_val: 1.0
