# @package model
_target_: project.lit_module.LitModel
# model hyperparams (example)
input_dim: 32
hidden_dim: 128
num_classes: 10
lr: 3e-4

# pass optimizer config into the module so configure_optimizers() can build it
optim: ${optim}
